open Parse_2018320190

let testcases_cfg : Parse.cfg list =
  [
    (* 1 *)   ([N "N"; N "N1"; N "N2"; N "N3"; N "B"; N "C"; N "D"], [T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T ","], N "N", [(N "N", []); (N "N", [N "N1"; N "B"]); (N "N1", [N "D"; N "N2";]); (N "N2", []); (N "N2", [N "D"; N "N3";]); (N "N3", []); (N "N3", [N "D"]); (N "B", []); (N "B", [N "C"; N "D"; N "D"; N "D"; N "B"]); (N "C", [T ","]); (N "D", [T "0"]); (N "D", [T "1"]); (N "D", [T "2"]); (N "D", [T "3"]); (N "D", [T "4"]); (N "D", [T "5"]); (N "D", [T "6"]); (N "D", [T "7"]); (N "D", [T "8"]); (N "D", [T "9"])])
    (* 2 *)   ([N "P"], [T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"], N "P", [(N "P", []); (N "P", [T "0"]); (N "P", [T "1"]); (N "P", [T "2"]); (N "P", [T "3"]); (N "P", [T "4"]); (N "P", [T "5"]); (N "P", [T "6"]); (N "P", [T "7"]); (N "P", [T "8"]); (N "P", [T "9"]); (N "P", [T "0"; N "P"; T "0"]); (N "P", [T "1"; N "P"; T "1"]); (N "P", [T "2"; N "P"; T "2"]); (N "P", [T "3"; N "P"; T "3"]); (N "P", [T "4"; N "P"; T "4"]); (N "P", [T "5"; N "P"; T "5"]); (N "P", [T "6"; N "P"; T "6"]); (N "P", [T "7"; N "P"; T "7"]); (N "P", [T "8"; N "P"; T "8"]); (N "P", [T "9"; N "P"; T "9"])])
    (* 3 *)   ([N "E"; N "E'"; N "T"; N "T'"; N "F"], [T "!"; T "||"; T "&&"; T "("; T ")"; T "True"; T "False"], N "E", [(N "E", [N "T"; N "E'"]); (N "E'", []); (N "E'", [T "||"; N "T"; N "E'"]); (N "T", [N "F"; N "T'"]); (N "T'", []); (N "T'", [T "&&"; N "F"; N "T'"]); (N "F", [T "!"; N "F"]); (N "F", [T "("; N "E"; T ")"]); (N "F", [T "True"]); (N "F", [T "False"])])
    (* 4 *)   ([N "S"; N "V"; N "W"], [T "("; T ")"; T "a"; T "b"; T "c"; T "d"], N "S", [(N "S", [T "("; N "S"; T ")"; N "V"; N "W"]); (N "S", [T "a"; N "S"; T "b"; N "V"; N "W"]); (N "S", [T "d"; N "V"; N "W"]); (N "V", [N "V"; T "a"]); (N "V", []); (N "W", [N "W"; T "c"]); (N "W", [])])
    (* 5 *)   ([N "S"; N "U"; N "V"; N "W"], [T "("; T ")"; T "a"; T "b"; T "c"; T "d"], N "S", [(N "S", [N "U"; N "V"; N "W"]); (N "U", [T "("; N "S"; T ")"]); (N "U", [T "a"; N "S"; T "b"]); (N "U", [T "d"]); (N "V", [T "a"; N "V"]); (N "V", []); (N "W", [T "c"; N "W"]); (N "W", [])])
    (* 6 *)   ([N "M"; N "L"; N "LC"; N "INT"; N "ID"; N "ID'"; N "STR"; N "WS"; N "WS'"; N "DG"; N "LT"; N "DQ"; N "CHAR"; N "CHAR'"],  [T "("; T ")"; T "\""; T " "; T "\\n"; T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T "a"; T "b"; T "c"; T "d"; T "e"; T "f"; T "g"; T "h"; T "i"; T "j"; T "k"; T "l"; T "m"; T "n"; T "o"; T "p"; T "q"; T "r"; T "s"; T "t"; T "u"; T "v"; T "w"; T "x"; T "y"; T "z"], N "M", [(N "M", [N "WS"; N "INT"; N "WS"]); (N "M", [N "WS"; N "ID"; N "WS"]); (N "M", [N "WS"; N "STR"; N "WS"]); (N "M", [N "WS"; N "L"; N "WS"]); (N "L", [T "("; N "WS"; N "LC"; T ")"]); (N "LC", []); (N "LC", [N "LC"; N "WS'"; N "M"]); (N "INT", [N "INT"; N "DG"]); (N "ID", [N "LT"; N "ID'"]); (N "ID'", []); (N "ID'", [N "ID'"; N "LT"]); (N "ID'", [N "ID'"; N "DG"]); (N "STR", [N "DQ"; N "CHAR"; N "DQ"]); (N "WS", []); (N "WS", [N "WS"; N "WS'"]); (N "WS'", [N "WS'"; T " "]); (N "WS'", [N "WS'"; T "\\n"]); (N "DG", [T "0"]); (N "DG", [T "1"]); (N "DG", [T "2"]); (N "DG", [T "3"]); (N "DG", [T "4"]); (N "DG", [T "5"]); (N "DG", [T "6"]); (N "DG", [T "7"]); (N "DG", [T "8"]); (N "DG", [T "9"]); (N "LT", [T "a"]); (N "LT", [T "b"]); (N "LT", [T "c"]); (N "LT", [T "d"]); (N "LT", [T "e"]); (N "LT", [T "f"]); (N "LT", [T "g"]); (N "LT", [T "h"]); (N "LT", [T "i"]); (N "LT", [T "j"]); (N "LT", [T "k"]); (N "LT", [T "l"]); (N "LT", [T "m"]); (N "LT", [T "n"]); (N "LT", [T "o"]); (N "LT", [T "p"]); (N "LT", [T "q"]); (N "LT", [T "r"]); (N "LT", [T "s"]); (N "LT", [T "t"]); (N "LT", [T "u"]); (N "LT", [T "v"]); (N "LT", [T "w"]); (N "LT", [T "x"]); (N "LT", [T "y"]); (N "LT", [T "z"]); (N "DQ", [T "\""]); (N "CHAR", []); (N "CHAR", [N "CHAR"; N "CHAR'"]); (N "CHAR'", [N "DG"]); (N "CHAR'", [N "LT"]); (N "CHAR'", [T " "])])
    (* 7 *)   ([N "M"; N "MSG"; N "L"; N "L'"; N "L''"; N "INT"; N "INT'"; N "ID"; N "ID'"; N "STR"; N "WS"; N "WS'"; N "DG"; N "LT"; N "DQ"; N "CHAR"; N "CHAR'"; N "WC"],  [T "("; T ")"; T "\""; T " "; T "\\n"; T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T "a"; T "b"; T "c"; T "d"; T "e"; T "f"; T "g"; T "h"; T "i"; T "j"; T "k"; T "l"; T "m"; T "n"; T "o"; T "p"; T "q"; T "r"; T "s"; T "t"; T "u"; T "v"; T "w"; T "x"; T "y"; T "z"],  N "M", [(N "M", [N "WS"; N "MSG"; N "WS"]); (N "MSG", [N "INT"]); (N "MSG", [N "ID"]); (N "MSG", [N "STR"]); (N "MSG", [N "L"]); (N "L", [T "("; N "WS"; N "L'"]); (N "L'", [T ")"]); (N "L'", [N "MSG"; N "L''"]); (N "L''", [T ")"]); (N "L''", [N "WS'"; N "L'"]); (N "INT", [N "DG"; N "INT'"]); (N "INT'", []); (N "INT'", [N "DG"; N "INT'"]); (N "ID", [N "LT"; N "ID'"]); (N "ID'", []); (N "ID'", [N "LT"; N "ID'"]); (N "ID'", [N "DG"; N "ID'"]); (N "STR", [N "DQ"; N "CHAR"; N "DQ"]); (N "WS", []); (N "WS", [N "WS'"]); (N "WS'", [N "WC"; N "WS"]); (N "DG", [T "0"]); (N "DG", [T "1"]); (N "DG", [T "2"]); (N "DG", [T "3"]); (N "DG", [T "4"]); (N "DG", [T "5"]); (N "DG", [T "6"]); (N "DG", [T "7"]); (N "DG", [T "8"]); (N "DG", [T "9"]); (N "LT", [T "a"]); (N "LT", [T "b"]); (N "LT", [T "c"]); (N "LT", [T "d"]); (N "LT", [T "e"]); (N "LT", [T "f"]); (N "LT", [T "g"]); (N "LT", [T "h"]); (N "LT", [T "i"]); (N "LT", [T "j"]); (N "LT", [T "k"]); (N "LT", [T "l"]); (N "LT", [T "m"]); (N "LT", [T "n"]); (N "LT", [T "o"]); (N "LT", [T "p"]); (N "LT", [T "q"]); (N "LT", [T "r"]); (N "LT", [T "s"]); (N "LT", [T "t"]); (N "LT", [T "u"]); (N "LT", [T "v"]); (N "LT", [T "w"]); (N "LT", [T "x"]); (N "LT", [T "y"]); (N "LT", [T "z"]); (N "DQ", [T "\""]); (N "CHAR", []); (N "CHAR", [N "CHAR'"; N "CHAR"]); (N "CHAR'", [N "DG"]); (N "CHAR'", [N "LT"]); (N "CHAR'", [T " "]); (N "WC", [T " "]); (N "WC", [T "\\n"])])
    (* 8 *)   ([N "stmt"; N "exprstmt"; N "ifstmt";], [T "0;"; T "1;"; T "if ("; T ") {"; T "}";], N "stmt", [(N "stmt", []); (N "stmt", [N "exprstmt"; N "stmt"]); (N "stmt", [N "ifstmt"  ; N "stmt"]); (N "exprstmt", [T "0;"]); (N "exprstmt", [T "1;"]); (N "ifstmt", [T "if ("; N "exprstmt"; T ") {"; N "stmt"; T "}"])])
    (* 9 *)   ([N "type"; N "arglist"; N "var"; N "arrtyp";], [T "int"; T "float"; T "x"; T "y"; T ","; T "["; T "]";], N "arglist", [(N "type", [T "int"; N "arrtyp"]); (N "type", [T "float"; N "arrtyp"]); (N "arrtyp", []); (N "arrtyp", [T "["; T "]"]); (N "arglist", []); (N "arglist", [N "type"; N "var"; T ","; N "arglist"]); (N "var", [T "x";]); (N "var", [T "y";])])
    (* 10 *)  ([N "S"; N "A"; N "B";], [T "a"; T "b";], N "S", [(N "S", [N "A"; T "a"; N "A"; T "b";]); (N "S", [N "B"; T "b"; N "B"; T "a";]); (N "A", []); (N "B", [])])
    (* 11 *)  ([N "S"], [T "a"; T "b"], N "S", [(N "S", [T "a"; N "S"; T "b"; N "S";]); (N "S", [T "b"; N "S"; T "a"; N "S";]); (N "S", [])])
    (* 12 *)  ([N "expr"; N "term"; N "factor";], [T "or"; T "and"; T "not"; T "true"; T "false"; T "("; T ")";], N "expr", [(N "expr", [N "expr"; T "or"; N "term";]); (N "expr", [N "term";]); (N "term", [N "term"; T "and"; N "factor";]); (N "term", [N "factor";]); (N "factor", [T "not"; N "factor"]); (N "factor", [T "("; N "expr"; T")";]); (N "factor", [T "true";]); (N "factor", [T "false";])])
    (* 13 *)  ([N "expr"; N "lvalue"; N "var";], [T "0"; T "1"; T "="; T "f"; T "x"; T "y"; T "*"; T "("; T ")";], N "expr", [(N "expr", [T "0"]); (N "expr", [T "1"]); (N "expr", [N "lvalue"]); (N "expr", [N "lvalue"; T "="; N "expr";]); (N "expr", [N "lvalue"; T "("; N "expr"; T ")";]); (N "lvalue", [N "var"]); (N "lvalue", [T "*"; N "lvalue";]); (N "var", [T "f"]); (N "var", [T "x"]); (N "var", [T "y"])])
    (* 14 *)  ([N "A"; N "B"; N "C"; N "S"], [T "a"; T "aa"; T "b"; T "bb"; T "c"; T "cc";], N "S", [(N "S", [N "A"; T "aa"; N "S"; N "S"; T "c";]); (N "S", [T "aa"; T "b"; N "S"; N "C";]); (N "A", [T "a"; T "b"; T "cc"; N "S";]); (N "A", []); (N "B", [N "S"; N "B"; T "b";]); (N "B", [N "A"; T "aa"; N "B"; T "bb";]); (N "B", []); (N "C", [T "cc"; T "c"; N "S"; T "cc";]); (N "C", [N "A"; N "S"; T "c"; N "C";])])
    (* 15 *)  ([N "K"; N "T"; N "T'"; N "C"; N "C'"], [T "a"; T "c"; T "t"], N "K", [(N "K", [N "T"; T "t"]); (N "T", [N "T'"; N "C"]); (N "T'", [T "c"]); (N "T'", []); (N "C", [T "a"]); (N "C", [N "C'"]); (N "C'", [])])
    (* 16 *)  ([N "S"; N "S'"; N "P"; N "P'"; N "U"; N "Y"], [T "p"; T "u"; T "i"; T "e"; T "s"; T "pp"], N "S", [(N "S", [N "P"; N "U"; N "S'"]); (N "S", [T "s"]); (N "S'", [N "P"; N "Y"]); (N "S'", []); (N "P", [T "p"]); (N "P", [T "pp"]); (N "U", [T "u"]); (N "U", []); (N "Y", [T "i"; T "e"; N "S"]); (N "Y", [])])
    (* 17 *)  ([N "S"; N "V"; N "V'"; N "C"; N "C'"; N "E"], [T "a"; T "e"; T "i"; T "u"; T "c"; T "o"; T "n"; T "g"; T "r"; T "t"; T "s"; T "!"; T "?"], N "S", [(N "S", [N "C"; N "V"; T "n"; N "C"; N "S"]); (N "S", [N "E"]); (N "C", [T "c"; N "C'"]); (N "C", [T "t"; N "C'"]); (N "C", [T "n"; N "C'"]); (N "C", [T "g"; N "C'"]); (N "C", [N "V"; N "C"]); (N "C'", [T "r"; N "C"]); (N "C'", [T "s"]); (N "C'", []); (N "V", [T "a"; N "V'"]); (N "V", [T "o"; N "V'"]); (N "V", [T "i"]); (N "V'", [T "u"; N "V"]); (N "V'", [T "e"]); (N "V'", []); (N "E", [T "!"]); (N "E", [T "?"]); (N "E", [])])
    (* 18 *)  ([N "S"; N "S'"; N "P"; N "P'"], [T "a"; T "b"; T "c"], N "S", [(N "S", [N "S'"; N "P"; N "P'"]); (N "S'", [N "P'"; T "a"; T "b"]); (N "S'", []); (N "P", [T "b"; N "P'"; T "a"]); (N "P", [T "a"]); (N "P", [T "b"]); (N "P'", [T "a"]); (N "P'", [T "c"]); (N "P'", [])])
    (* 19 *)  ([N "K"; N "T"; N "T'"; N "C"; N "C'"], [T "a"; T "c"; T "t"], N "K", [(N "K", [N "T"; T "t"]); (N "T", [N "T'"; N "C"]); (N "T'", [T "c"]); (N "T'", [T "t"]); (N "T'", []); (N "C", [T "a"]); (N "C", [N "C'"]); (N "C'", [])])
    (* 20 *)  ([N "S"; N "V"; N "V'"; N "C"; N "C'"; N "E"], [T "a"; T "e"; T "i"; T "o"; T "u"; T "c"; T "m"; T "p"; T "r"; T "l"; T "s"; T "!"; T "?"], N "S", [(N "S", [N "C"; N "V"; T "m"; N "C"; N "S"]); (N "S", [N "E"]); (N "C", [N "V"; N "C"; N "C'"]); (N "C", [T "m"; N "C'"; N "V"]); (N "C", [T "c"; N "C'"]); (N "C", [T "l"]); (N "C'", [T "p"; N "C"]); (N "C'", [T "r"; N "C'"]); (N "C'", [T "s"; N "C'"]); (N "C'", []); (N "V", [T "a"; N "V'"]); (N "V", [T "o"; N "V'"]); (N "V", [T "i"]); (N "V'", [T "u"; N "V"]); (N "V'", [T "e"]); (N "V'", []); (N "E", [T "!"]); (N "E", [T "?"]); (N "E", [])])
  ]

let testcases_sentence : (Parse.symbol list * Parse.cfg) list =
  [
    (* 1 *)   ([T "1"; T "3"; T "2"; T ","; T "4"; T "7"; T "6"; T ","; T "5"; T "9"; T "8"; End], ([N "N"; N "N1"; N "N2"; N "N3"; N "B"; N "C"; N "D"], [T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T ","], N "N", [(N "N", []); (N "N", [N "N1"; N "B"]); (N "N1", [N "D"; N "N2";]); (N "N2", []); (N "N2", [N "D"; N "N3";]); (N "N3", []); (N "N3", [N "D"]); (N "B", []); (N "B", [N "C"; N "D"; N "D"; N "D"; N "B"]); (N "C", [T ","]); (N "D", [T "0"]); (N "D", [T "1"]); (N "D", [T "2"]); (N "D", [T "3"]); (N "D", [T "4"]); (N "D", [T "5"]); (N "D", [T "6"]); (N "D", [T "7"]); (N "D", [T "8"]); (N "D", [T "9"])]))
    (* 2 *)   ([T "1"; T "3"; T "2"; T ","; T "4"; T "7"; T "6"; T ","; T "5"; T "9"; End], ([N "N"; N "N1"; N "N2"; N "N3"; N "B"; N "C"; N "D"], [T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T ","], N "N", [(N "N", []); (N "N", [N "N1"; N "B"]); (N "N1", [N "D"; N "N2";]); (N "N2", []); (N "N2", [N "D"; N "N3";]); (N "N3", []); (N "N3", [N "D"]); (N "B", []); (N "B", [N "C"; N "D"; N "D"; N "D"; N "B"]); (N "C", [T ","]); (N "D", [T "0"]); (N "D", [T "1"]); (N "D", [T "2"]); (N "D", [T "3"]); (N "D", [T "4"]); (N "D", [T "5"]); (N "D", [T "6"]); (N "D", [T "7"]); (N "D", [T "8"]); (N "D", [T "9"])]))
    (* 3 *)   ([T "1"; T "3"; T "2"; T ","; T "4"; T "7";T ","; T "5"; T "9"; T "8"; End], ([N "N"; N "N1"; N "N2"; N "N3"; N "B"; N "C"; N "D"], [T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T ","], N "N", [(N "N", []); (N "N", [N "N1"; N "B"]); (N "N1", [N "D"; N "N2";]); (N "N2", []); (N "N2", [N "D"; N "N3";]); (N "N3", []); (N "N3", [N "D"]); (N "B", []); (N "B", [N "C"; N "D"; N "D"; N "D"; N "B"]); (N "C", [T ","]); (N "D", [T "0"]); (N "D", [T "1"]); (N "D", [T "2"]); (N "D", [T "3"]); (N "D", [T "4"]); (N "D", [T "5"]); (N "D", [T "6"]); (N "D", [T "7"]); (N "D", [T "8"]); (N "D", [T "9"])]))
    (* 4 *)   ([T "("; T "True"; T "||"; T "False"; T ")"; T "&&"; T "True"; End], ([N "E"; N "E'"; N "T"; N "T'"; N "F"], [T "!"; T "||"; T "&&"; T "("; T ")"; T "True"; T "False"], N "E", [(N "E", [N "T"; N "E'"]); (N "E'", []); (N "E'", [T "||"; N "T"; N "E'"]); (N "T", [N "F"; N "T'"]); (N "T'", []); (N "T'", [T "&&"; N "F"; N "T'"]); (N "F", [T "!"; N "F"]); (N "F", [T "("; N "E"; T ")"]); (N "F", [T "True"]); (N "F", [T "False"])]))
    (* 5 *)   ([T "a"; T "a"; T "b"; T "b"; T "a"; T "c"; T "a"; End], ([N "S"; N "U"; N "V"; N "W"], [T "("; T ")"; T "a"; T "b"; T "c"; T "d"], N "S", [(N "S", [N "U"; N "V"; N "W"]); (N "U", [T "("; N "S"; T ")"]); (N "U", [T "a"; N "S"; T "b"]); (N "U", [T "d"]); (N "V", [T "a"; N "V"]); (N "V", []); (N "W", [T "c"; N "W"]); (N "W", [])]))
    (* 6 *)   ([T "a"; T "("; T "a"; T "d"; T "b"; T "c"; T "c"; T ")"; T "a"; T "b"; T "a"; T "a"; T "a"; T "c"; T "c"; T "c"; End], ([N "S"; N "U"; N "V"; N "W"], [T "("; T ")"; T "a"; T "b"; T "c"; T "d"], N "S", [(N "S", [N "U"; N "V"; N "W"]); (N "U", [T "("; N "S"; T ")"]); (N "U", [T "a"; N "S"; T "b"]); (N "U", [T "d"]); (N "V", [T "a"; N "V"]); (N "V", []); (N "W", [T "c"; N "W"]); (N "W", [])]))
    (* 7 *)   ([T "0"; T "5"; T "2"; T "3"; T "j"; End], ([N "M"; N "MSG"; N "L"; N "L'"; N "L''"; N "INT"; N "INT'"; N "ID"; N "ID'"; N "STR"; N "WS"; N "WS'"; N "DG"; N "LT"; N "DQ"; N "CHAR"; N "CHAR'"; N "WC"],  [T "("; T ")"; T "\""; T " "; T "\\n"; T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T "a"; T "b"; T "c"; T "d"; T "e"; T "f"; T "g"; T "h"; T "i"; T "j"; T "k"; T "l"; T "m"; T "n"; T "o"; T "p"; T "q"; T "r"; T "s"; T "t"; T "u"; T "v"; T "w"; T "x"; T "y"; T "z"],  N "M", [(N "M", [N "WS"; N "MSG"; N "WS"]); (N "MSG", [N "INT"]); (N "MSG", [N "ID"]); (N "MSG", [N "STR"]); (N "MSG", [N "L"]); (N "L", [T "("; N "WS"; N "L'"]); (N "L'", [T ")"]); (N "L'", [N "MSG"; N "L''"]); (N "L''", [T ")"]); (N "L''", [N "WS'"; N "L'"]); (N "INT", [N "DG"; N "INT'"]); (N "INT'", []); (N "INT'", [N "DG"; N "INT'"]); (N "ID", [N "LT"; N "ID'"]); (N "ID'", []); (N "ID'", [N "LT"; N "ID'"]); (N "ID'", [N "DG"; N "ID'"]); (N "STR", [N "DQ"; N "CHAR"; N "DQ"]); (N "WS", []); (N "WS", [N "WS'"]); (N "WS'", [N "WC"; N "WS"]); (N "DG", [T "0"]); (N "DG", [T "1"]); (N "DG", [T "2"]); (N "DG", [T "3"]); (N "DG", [T "4"]); (N "DG", [T "5"]); (N "DG", [T "6"]); (N "DG", [T "7"]); (N "DG", [T "8"]); (N "DG", [T "9"]); (N "LT", [T "a"]); (N "LT", [T "b"]); (N "LT", [T "c"]); (N "LT", [T "d"]); (N "LT", [T "e"]); (N "LT", [T "f"]); (N "LT", [T "g"]); (N "LT", [T "h"]); (N "LT", [T "i"]); (N "LT", [T "j"]); (N "LT", [T "k"]); (N "LT", [T "l"]); (N "LT", [T "m"]); (N "LT", [T "n"]); (N "LT", [T "o"]); (N "LT", [T "p"]); (N "LT", [T "q"]); (N "LT", [T "r"]); (N "LT", [T "s"]); (N "LT", [T "t"]); (N "LT", [T "u"]); (N "LT", [T "v"]); (N "LT", [T "w"]); (N "LT", [T "x"]); (N "LT", [T "y"]); (N "LT", [T "z"]); (N "DQ", [T "\""]); (N "CHAR", []); (N "CHAR", [N "CHAR'"; N "CHAR"]); (N "CHAR'", [N "DG"]); (N "CHAR'", [N "LT"]); (N "CHAR'", [T " "]); (N "WC", [T " "]); (N "WC", [T "\\n"])]))
    (* 8 *)   ([T "("; T "i"; T "d"; T "9"; T "4"; T "\\n"; T "0"; T "4"; T "0"; T "6"; T " "; T "\""; T "j"; T " "; T "1"; T "3"; T "\""; T ")"; End], ([N "M"; N "MSG"; N "L"; N "L'"; N "L''"; N "INT"; N "INT'"; N "ID"; N "ID'"; N "STR"; N "WS"; N "WS'"; N "DG"; N "LT"; N "DQ"; N "CHAR"; N "CHAR'"; N "WC"],  [T "("; T ")"; T "\""; T " "; T "\\n"; T "0"; T "1"; T "2"; T "3"; T "4"; T "5"; T "6"; T "7"; T "8"; T "9"; T "a"; T "b"; T "c"; T "d"; T "e"; T "f"; T "g"; T "h"; T "i"; T "j"; T "k"; T "l"; T "m"; T "n"; T "o"; T "p"; T "q"; T "r"; T "s"; T "t"; T "u"; T "v"; T "w"; T "x"; T "y"; T "z"],  N "M", [(N "M", [N "WS"; N "MSG"; N "WS"]); (N "MSG", [N "INT"]); (N "MSG", [N "ID"]); (N "MSG", [N "STR"]); (N "MSG", [N "L"]); (N "L", [T "("; N "WS"; N "L'"]); (N "L'", [T ")"]); (N "L'", [N "MSG"; N "L''"]); (N "L''", [T ")"]); (N "L''", [N "WS'"; N "L'"]); (N "INT", [N "DG"; N "INT'"]); (N "INT'", []); (N "INT'", [N "DG"; N "INT'"]); (N "ID", [N "LT"; N "ID'"]); (N "ID'", []); (N "ID'", [N "LT"; N "ID'"]); (N "ID'", [N "DG"; N "ID'"]); (N "STR", [N "DQ"; N "CHAR"; N "DQ"]); (N "WS", []); (N "WS", [N "WS'"]); (N "WS'", [N "WC"; N "WS"]); (N "DG", [T "0"]); (N "DG", [T "1"]); (N "DG", [T "2"]); (N "DG", [T "3"]); (N "DG", [T "4"]); (N "DG", [T "5"]); (N "DG", [T "6"]); (N "DG", [T "7"]); (N "DG", [T "8"]); (N "DG", [T "9"]); (N "LT", [T "a"]); (N "LT", [T "b"]); (N "LT", [T "c"]); (N "LT", [T "d"]); (N "LT", [T "e"]); (N "LT", [T "f"]); (N "LT", [T "g"]); (N "LT", [T "h"]); (N "LT", [T "i"]); (N "LT", [T "j"]); (N "LT", [T "k"]); (N "LT", [T "l"]); (N "LT", [T "m"]); (N "LT", [T "n"]); (N "LT", [T "o"]); (N "LT", [T "p"]); (N "LT", [T "q"]); (N "LT", [T "r"]); (N "LT", [T "s"]); (N "LT", [T "t"]); (N "LT", [T "u"]); (N "LT", [T "v"]); (N "LT", [T "w"]); (N "LT", [T "x"]); (N "LT", [T "y"]); (N "LT", [T "z"]); (N "DQ", [T "\""]); (N "CHAR", []); (N "CHAR", [N "CHAR'"; N "CHAR"]); (N "CHAR'", [N "DG"]); (N "CHAR'", [N "LT"]); (N "CHAR'", [T " "]); (N "WC", [T " "]); (N "WC", [T "\\n"])]))
    (* 9 *)   ([T "1;"; T "0;"; T "if ("; T "0;"; T ") {"; T "if ("; T "1;"; T ") {"; T "}"; T "0;"; T "}"; End], ([N "stmt"; N "exprstmt"; N "ifstmt";], [T "0;"; T "1;"; T "if ("; T ") {"; T "}";], N "stmt", [(N "stmt", []); (N "stmt", [N "exprstmt"; N "stmt"]); (N "stmt", [N "ifstmt"  ; N "stmt"]); (N "exprstmt", [T "0;"]); (N "exprstmt", [T "1;"]); (N "ifstmt", [T "if ("; N "exprstmt"; T ") {"; N "stmt"; T "}"])]))
    (* 10 *)  ([T "if ("; T "1;"; T ") {"; T "if ("; T "1;"; T "}"; T "if ("; T "0;"; T ") {"; T "}"; End], ([N "stmt"; N "exprstmt"; N "ifstmt";], [T "0;"; T "1;"; T "if ("; T ") {"; T "}";], N "stmt", [(N "stmt", []); (N "stmt", [N "exprstmt"; N "stmt"]); (N "stmt", [N "ifstmt"  ; N "stmt"]); (N "exprstmt", [T "0;"]); (N "exprstmt", [T "1;"]); (N "ifstmt", [T "if ("; N "exprstmt"; T ") {"; N "stmt"; T "}"])]))
    (* 11 *)  ([T "int"; T "y"; T ","; T "float"; T "["; T "]"; T "x"; T ","; T "float"; T "x"; T ","; End], ([N "type"; N "arglist"; N "var"; N "arrtyp";], [T "int"; T "float"; T "x"; T "y"; T ","; T "["; T "]";], N "arglist", [(N "type", [T "int"; N "arrtyp"]); (N "type", [T "float"; N "arrtyp"]); (N "arrtyp", []); (N "arrtyp", [T "["; T "]"]); (N "arglist", []); (N "arglist", [N "type"; N "var"; T ","; N "arglist"]); (N "var", [T "x";]); (N "var", [T "y";])]))
    (* 12 *)  ([T "int"; T "y"; T ","; T "float"; T "["; T "]"; T "x"; T ","; T "float"; T ","; T ","; End], ([N "type"; N "arglist"; N "var"; N "arrtyp";], [T "int"; T "float"; T "x"; T "y"; T ","; T "["; T "]";], N "arglist", [(N "type", [T "int"; N "arrtyp"]); (N "type", [T "float"; N "arrtyp"]); (N "arrtyp", []); (N "arrtyp", [T "["; T "]"]); (N "arglist", []); (N "arglist", [N "type"; N "var"; T ","; N "arglist"]); (N "var", [T "x";]); (N "var", [T "y";])]))
    (* 13 *)  ([T "b"; T "a"; End], ([N "S"; N "A"; N "B";], [T "a"; T "b";], N "S", [(N "S", [N "A"; T "a"; N "A"; T "b";]); (N "S", [N "B"; T "b"; N "B"; T "a";]); (N "A", []); (N "B", [])]))
    (* 14 *)  ([T "a"; T "a"; End], ([N "S"; N "A"; N "B";], [T "a"; T "b";], N "S", [(N "S", [N "A"; T "a"; N "A"; T "b";]); (N "S", [N "B"; T "b"; N "B"; T "a";]); (N "A", []); (N "B", [])]))
    (* 15 *)  ([T "c"; T "a"; T "t"; End], ([N "K"; N "T"; N "T'"; N "C"; N "C'"], [T "a"; T "c"; T "t"], N "K", [(N "K", [N "T"; T "t"]); (N "T", [N "T'"; N "C"]); (N "T'", [T "c"]); (N "T'", []); (N "C", [T "a"]); (N "C", [N "C'"]); (N "C'", [])]))
    (* 16 *)  ([T "p"; T "u"; T "p"; T "p"; T "i"; T "e"; T "s"; End], ([N "S"; N "S'"; N "P"; N "P'"; N "U"; N "Y"], [T "p"; T "u"; T "i"; T "e"; T "s"; T "pp"], N "S", [(N "S", [N "P"; N "U"; N "S'"]); (N "S", [T "s"]); (N "S'", [N "P"; N "Y"]); (N "S'", []); (N "P", [T "p"]); (N "P", [T "pp"]); (N "U", [T "u"]); (N "U", []); (N "Y", [T "i"; T "e"; N "S"]); (N "Y", [])]))
    (* 17 *)  ([T "p"; T "u"; T "pp"; T "i"; T "e"; T "s"; End], ([N "S"; N "S'"; N "P"; N "P'"; N "U"; N "Y"], [T "p"; T "u"; T "i"; T "e"; T "s"; T "pp"], N "S", [(N "S", [N "P"; N "U"; N "S'"]); (N "S", [T "s"]); (N "S'", [N "P"; N "Y"]); (N "S'", []); (N "P", [T "p"]); (N "P", [T "pp"]); (N "U", [T "u"]); (N "U", []); (N "Y", [T "i"; T "e"; N "S"]); (N "Y", [])]))
    (* 18 *)  ([T "c"; T "o"; T "n"; T "g"; T "r"; T "a"; T "t"; T "s"; T "!"; End], ([N "S"; N "V"; N "V'"; N "C"; N "C'"; N "E"], [T "a"; T "e"; T "i"; T "u"; T "c"; T "o"; T "n"; T "g"; T "r"; T "t"; T "s"; T "!"; T "?"], N "S", [(N "S", [N "C"; N "V"; T "n"; N "C"; N "S"]); (N "S", [N "E"]); (N "C", [T "c"; N "C'"]); (N "C", [T "t"; N "C'"]); (N "C", [T "n"; N "C'"]); (N "C", [T "g"; N "C'"]); (N "C", [N "V"; N "C"]); (N "C'", [T "r"; N "C"]); (N "C'", [T "s"]); (N "C'", []); (N "V", [T "a"; N "V'"]); (N "V", [T "o"; N "V'"]); (N "V", [T "i"]); (N "V'", [T "u"; N "V"]); (N "V'", [T "e"]); (N "V'", []); (N "E", [T "!"]); (N "E", [T "?"]); (N "E", [])]))
    (* 19 *)  ([T "c"; T "o"; T "n"; T "c"; T "e"; T "r"; T "n"; T "!"; End], ([N "S"; N "V"; N "V'"; N "C"; N "C'"; N "E"], [T "a"; T "e"; T "i"; T "u"; T "c"; T "o"; T "n"; T "g"; T "r"; T "t"; T "s"; T "!"; T "?"], N "S", [(N "S", [N "C"; N "V"; T "n"; N "C"; N "S"]); (N "S", [N "E"]); (N "C", [T "c"; N "C'"]); (N "C", [T "t"; N "C'"]); (N "C", [T "n"; N "C'"]); (N "C", [T "g"; N "C'"]); (N "C", [N "V"; N "C"]); (N "C'", [T "r"; N "C"]); (N "C'", [T "s"]); (N "C'", []); (N "V", [T "a"; N "V'"]); (N "V", [T "o"; N "V'"]); (N "V", [T "i"]); (N "V'", [T "u"; N "V"]); (N "V'", [T "e"]); (N "V'", []); (N "E", [T "!"]); (N "E", [T "?"]); (N "E", [])]))
    (* 20 *)  ([T "c"; T "o"; T "n"; T "o"; T "e"; T "s"; T "!"; End], ([N "S"; N "V"; N "V'"; N "C"; N "C'"; N "E"], [T "a"; T "e"; T "i"; T "u"; T "c"; T "o"; T "n"; T "g"; T "r"; T "t"; T "s"; T "!"; T "?"], N "S", [(N "S", [N "C"; N "V"; T "n"; N "C"; N "S"]); (N "S", [N "E"]); (N "C", [T "c"; N "C'"]); (N "C", [T "t"; N "C'"]); (N "C", [T "n"; N "C'"]); (N "C", [T "g"; N "C'"]); (N "C", [N "V"; N "C'"]); (N "C'", [T "r"; N "C"]); (N "C'", [T "s"]); (N "C'", []); (N "V", [T "a"; N "V'"]); (N "V", [T "o"; N "V'"]); (N "V", [T "i"]); (N "V'", [T "u"; N "V"]); (N "V'", [T "e"]); (N "V'", []); (N "E", [T "!"]); (N "E", [T "?"]); (N "E", [])]))
  ]

let main () =
  List.iter (fun cfg ->
    print_endline (string_of_bool (check_LL1 cfg))
  ) testcases_cfg;
  print_endline "";
  List.iter (fun (sentence, cfg) ->
    print_endline (string_of_bool (parse cfg sentence))
  ) testcases_sentence

let _ = main ()
